export enum UserRole {
  CUSTOMER = 'CUSTOMER',
  SUPER_ADMIN = 'SUPER_ADMIN',
  ADMIN = 'ADMIN',
  CLAIM_OFFICER = 'CLAIM_OFFICER',
  FINANCE_OFFICER = 'FINANCE_OFFICER',
  MANAGER = 'MANAGER',
  BRANCH_MANAGER = 'BRANCH_MANAGER',
  AGENT = 'AGENT',
  ASSESSOR = 'ASSESSOR',
}

export enum UserStatus {
  ACTIVE = 'ACTIVE',
  INACTIVE = 'INACTIVE',
  SUSPENDED = 'SUSPENDED',
}

export enum ProductStatus {
  ACTIVE = 'ACTIVE',
  INACTIVE = 'INACTIVE',
}

export enum QuotationStatus {
  DRAFT = 'DRAFT',
  SUBMITTED = 'SUBMITTED',
  FINANCE_APPROVED = 'FINANCE_APPROVED',
  MANAGER_APPROVED = 'MANAGER_APPROVED',
  APPROVED = 'APPROVED',
  REJECTED = 'REJECTED',
  EXPIRED = 'EXPIRED',
}

export enum PolicyStatus {
  PENDING_PAYMENT = 'PENDING_PAYMENT',
  ACTIVE = 'ACTIVE',
  EXPIRED = 'EXPIRED',
  CANCELLED = 'CANCELLED',
  SUSPENDED = 'SUSPENDED',
}

export enum PaymentMethod {
  BANK_TRANSFER = 'BANK_TRANSFER',
  TELEBIRR = 'TELEBIRR',
  CHAPA = 'CHAPA',
  CASH = 'CASH',
  OTHER = 'OTHER',
}

export enum PaymentStatus {
  PENDING = 'PENDING',
  VERIFIED = 'VERIFIED',
  REJECTED = 'REJECTED',
  FAILED = 'FAILED',
  REFUNDED = 'REFUNDED',
}

export enum ClaimStatus {
  SUBMITTED = 'SUBMITTED',
  DOCUMENT_REVIEW = 'DOCUMENT_REVIEW',
  MORE_INFO_REQUIRED = 'MORE_INFO_REQUIRED',
  ASSIGNED_TO_ASSESSOR = 'ASSIGNED_TO_ASSESSOR',
  ASSESSMENT_COMPLETED = 'ASSESSMENT_COMPLETED',
  PENDING_APPROVAL = 'PENDING_APPROVAL',
  APPROVED = 'APPROVED',
  REJECTED = 'REJECTED',
  SETTLEMENT_PROCESSING = 'SETTLEMENT_PROCESSING',
  SETTLED = 'SETTLED',
  CLOSED = 'CLOSED',
}

export enum DocumentOwnerType {
  CUSTOMER = 'CUSTOMER',
  QUOTATION = 'QUOTATION',
  POLICY = 'POLICY',
  CLAIM = 'CLAIM',
  PAYMENT = 'PAYMENT',
}

export enum DocumentStatus {
  PENDING_REVIEW = 'PENDING_REVIEW',
  APPROVED = 'APPROVED',
  REJECTED = 'REJECTED',
}
